In [193]:
import pandas as pd
import numpy as np
import csv
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn import tree
import matplotlib.pyplot as mt
%matplotlib inline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import MinMaxScaler
loocv = LeaveOneOut()

In [55]:
leaf_dataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Class                      340 non-null    int64  
 1   Specimen No                340 non-null    int64  
 2   Eccentricity               340 non-null    float64
 3   Aspect Ratio               340 non-null    float64
 4   Elongation                 340 non-null    float64
 5    Solidity                  340 non-null    float64
 6   Stochastic Convexity       340 non-null    float64
 7   Isoperimetric Factor       340 non-null    float64
 8   Maximal Indentation Depth  340 non-null    float64
 9    Lobedness                 340 non-null    float64
 10  Average Intensity          340 non-null    float64
 11  Average Contrast           340 non-null    float64
 12  Smoothness                 340 non-null    float64
 13  Third moment               340 non-null    float64

In [56]:
#dividing cloumns
X = leaf_dataSet.iloc[:, 0] #class column is our target
Y = leaf_dataSet.drop(columns=['Class','Specimen No']) #removing class and specimen no from Y data set

# without Normalizing 

# 1.data test-size = 75% and train-size =25

In [95]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(X,Y,test_size=0.25 ) # 0.25 == 25% test size
print('X-train =',x_train1.shape)
print('X-test =',x_test1.shape)
print('Y-train =',y_train1.shape)
print('Y-test =',y_test1.shape)

X-train = (255,)
X-test = (85,)
Y-train = (255, 14)
Y-test = (85, 14)


In [89]:
decision_tree=DecisionTreeClassifier(criterion = 'gini', random_state = 0)
decision_tree.fit(y_train1,x_train1)

DecisionTreeClassifier(random_state=0)

In [119]:
y_pred1=decision_tree.predict(y_test1)

In [120]:
print("Accuracy:",metrics.accuracy_score(x_test1, y_pred1))

Accuracy: 0.8470588235294118


In [126]:
d1 = tree.DecisionTreeClassifier(max_depth=100)
score1 = cross_val_score(d1, y_train1, x_train1, cv=loocv)
score1

array([1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 0.

In [135]:
np.mean(score1)

0.5529411764705883

# Normalizing Data

In [191]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
scaler = StandardScaler()
scaler.fit(y_train1)

y_data_train1 = scaler.transform(y_train1)
y_data_test1 = scaler.transform(y_test1)

y_data_train1 = Normalizer().fit_transform(y_train1)
y_data_test1 = Normalizer().fit(y_train1).transform(y_test1)

In [192]:
decision_treeN1=DecisionTreeClassifier(criterion = 'gini', random_state = 0)
decision_treeN1.fit(y_data_train1,x_train1)
y_pred1=decision_tree.predict(y_data_test1)
print("Accuracy:",metrics.accuracy_score(x_test1, y_pred1))

Accuracy: 0.4470588235294118


In [176]:
dN1 = tree.DecisionTreeClassifier(max_depth=100)
scoreN1 = cross_val_score(d1, y_data_train1, x_train1, cv=loocv)
scoreN1

array([1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0.

In [177]:
np.mean(scoreN1)

0.615686274509804

# 2.data test-size =0.66% and train-size =0.33%

In [128]:
x_train2, x_test2, y_train2, y_test2 = train_test_split(X,Y,test_size=0.33, random_state = 0 ) 
print('X-train =',x_train2.shape)
print('X-test =',x_test2.shape)
print('Y-train =',y_train2.shape)
print('Y-test =',y_test2.shape)

X-train = (227,)
X-test = (113,)
Y-train = (227, 14)
Y-test = (113, 14)


In [140]:
decision_tree2=DecisionTreeClassifier(criterion = 'gini', random_state = 0)
decision_tree2.fit(y_train2,x_train2)

DecisionTreeClassifier(random_state=0)

In [141]:
y_pred2=decision_tree2.predict(y_test2)

In [131]:
print("Accuracy:",metrics.accuracy_score(x_test2, y_pred2))

Accuracy: 0.584070796460177


In [142]:
d2 = tree.DecisionTreeClassifier(max_depth=100)
score2 = cross_val_score(d2, y_train2, x_train2, cv=loocv)
score2

array([1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 1.

In [152]:
np.mean(score2)

0.5418502202643172

# Normalizing data

In [178]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
scaler = StandardScaler()
scaler.fit(y_train2)

y_data_train2 = scaler.transform(y_train2)
y_data_test2 = scaler.transform(y_test2)

y_data_train2 = Normalizer().fit_transform(y_train2)
y_data_test2 = Normalizer().fit(y_train2).transform(y_test2)

In [179]:
decision_treeN2=DecisionTreeClassifier(criterion = 'gini', random_state = 0)
decision_treeN2.fit(y_data_train2,x_train2)
y_pred2=decision_tree.predict(y_data_test2)
print("Accuracy:",metrics.accuracy_score(x_test2, y_pred2))

Accuracy: 0.8495575221238938


In [181]:
dN2 = tree.DecisionTreeClassifier(max_depth=100)
scoreN2 = cross_val_score(d2, y_data_train2, x_train2, cv=loocv)
scoreN2

array([0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1.

In [184]:
np.mean(scoreN2)

0.5330396475770925

# 3.data test-size =0.50% and train-size =0.50%

# Non-normalized data 

In [137]:
x_train3, x_test3, y_train3, y_test3 = train_test_split(X,Y,test_size=0.50, random_state = 0 ) 
print('X-train =',x_train3.shape)
print('X-test =',x_test3.shape)
print('Y-train =',y_train3.shape)
print('Y-test =',y_test3.shape)

X-train = (170,)
X-test = (170,)
Y-train = (170, 14)
Y-test = (170, 14)


In [139]:
decision_tree3=DecisionTreeClassifier(criterion = 'gini', random_state = 0)
decision_tree3.fit(y_train3,x_train3)

DecisionTreeClassifier(random_state=0)

In [147]:
y_pred3=decision_tree2.predict(y_test3)

In [148]:
print("Accuracy:",metrics.accuracy_score(x_test3, y_pred3))

Accuracy: 0.7235294117647059


In [150]:
d3 = tree.DecisionTreeClassifier(max_depth=100)
score3 = cross_val_score(d3, y_train3, x_train3, cv=loocv)
score3

array([1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.])

In [154]:
np.mean(score3)

0.5294117647058824

# Normalizing data

In [187]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
scaler = StandardScaler()
scaler.fit(y_train3)

y_data_train3 = scaler.transform(y_train3)
y_data_test3 = scaler.transform(y_test3)

y_data_train3 = Normalizer().fit_transform(y_train3)
y_data_test3 = Normalizer().fit(y_train3).transform(y_test3)

In [188]:
decision_treeN3=DecisionTreeClassifier(criterion = 'gini', random_state = 0)
decision_treeN3.fit(y_data_train3,x_train3)
y_pred3=decision_tree.predict(y_data_test3)
print("Accuracy:",metrics.accuracy_score(x_test3, y_pred3))

Accuracy: 0.8411764705882353


In [189]:
dN3 = tree.DecisionTreeClassifier(max_depth=100)
scoreN3 = cross_val_score(d2, y_data_train3, x_train3, cv=loocv)
scoreN3

array([1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
       1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.])

In [190]:
np.mean(score3)

0.5294117647058824

# Conclusion 
when ever we Normalize and standardize our data we recive highest ammount of acccuracy..